### ISSUE TITLE
Running the server with no creds 

### ISSUE THREAD

**Issue by 9Al** [oasis-open/cti-taxii-server#141]
Can I run taxii server without credentials ? I tried to remove the creds from the config file but it gives me  a default user and pass.

**Comment by zrush-mitre** [comment]
Hi @9Al,

I have added a parameter to the medallion server to allow you to run it with no credentials. This turned out to be more difficult than anticipated, since we pass off authentication to a flask extension, but it did get implemented. You can find it on PR#142, and on the `no_auth_param` branch. It has not been merged onto master, as currently there is an issue around getting it to work on the test suite. At some point, hopefully this issue will get solved and it can get merged into master, but you can find the necessary code on that branch, and merge them as needed when master gets updated as well.

Let me know if you have any more questions.

Thanks.

**Comment by clenk** [comment]
I'm closing this for now, but please reopen or make a new issue if this didn't help.
