### ISSUE TITLE
Write OpenAPI specification

### ISSUE THREAD

**Issue by abreksa4** [oasis-open/cti-taxii-server#32]
Not sure if this is the place to put it, or if it exists and I missed it, but seems as if having an OpenAPI specification in place could help cut integration and on-boarding time due to [documention](https://github.com/swagger-api/swagger-ui) and [client/server generation](https://github.com/swagger-api/swagger-codegen). 

Don't have a problem putting one together with the resources available for 2.0, but want to know if it's desired.  

I can also ping the mailing list of that's a more appropriate forum for questions like these.

**Comment by gtback** [comment]
Hi @abreksa4, that's a great idea. It would be very cool if TAXII 2.0 (or 2.1) could be specified with an OpenAPI/Swagger spec.

It would probably end up being a different repository than this one (which we could then deprecate).

**Comment by gtback** [comment]
@abreksa4 have you had a chance to look into this? I don't think any of the current maintainers have the cycles to devote to this right now.

**Comment by abreksa4** [comment]
@gtback I can spend a bit of time working with this. I'll update this issue with a pointer to the working doc once it's put together.

**Comment by abreksa4** [comment]
@gtback I've put a rough version of the OpenAPI doc here: https://github.com/ThreatDataScience/taxii2-openapi

**Comment by gtback** [comment]
@abreksa4 Very cool! I haven't had time to actually try generating code from the OpenAPI definition, but I think a lot of people would find this interesting. I'd suggest posting this to the [cti-users list](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback).

Meanwhile, I'm going to close this issue, since I imagine that any server code generated from the specification will be in its own repo, not this one. If people find that useful, we may end up deprecating this repo, but I don't think we'll change this repo. 

Thanks again for taking the time to write the OpenAPI definition for TAXII!

**Comment by abreksa4** [comment]
@gtback No problem! I wasn't suggesting that this implmentaion be replaced with generated code from the OpenAPI doc, just that it provides a companion document to the existing specification, specifically one that allows for on-boarding developers to Taxii 2.0 in an industry-standard way. One of the first things I do is look for an OpenAPI spec or similar when integrating third-party (and even internal) HTTP serivces. 

I'll definitley shoot a message to cti-users when I get a chance.
